sylius_resource:
    settings:
        sortable: true
        filterable: true
        paginate: $paginate

parameters:
    locale: es
    locales: [es, en]
    stof_doctrine_extensions.event_listener.locale.class: Positibe\Bundle\CoreBundle\EventListener\LocaleListener
    positibe_core.sorting_template: PositibeCoreBundle:Grid:_sorting.html.twig

stof_doctrine_extensions:
    default_locale: %locale%
    translation_fallback: true
    orm:
        default:
#            tree: true
            sluggable: true
            timestampable: true
            translatable: true
#            softdeleteable: true
#            loggable: true
            sortable: true

doctrine:
    orm:
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"