positibe_core_entity_filter:
    path: /filter_entity
    defaults: { _controller: PositibeCoreBundle:Filter:getEntityFilter }

positibe_core_enum_filter:
    path: /filter_enum/{type}/{selected}
    defaults: { _controller: PositibeCoreBundle:Filter:getEnumFilter }

positibe_core_method_filter:
    path: /filter_method/{class}/{method}/{selected}
    defaults: { _controller: PositibeCoreBundle:Filter:getMethodFilter }

positibe_core_api_entity_ajax:
    path: /filter_entity_ajax
    defaults: { _controller: PositibeCoreBundle:Filter:apiEntityAjax }