services:
    positibe_core.core_extension:
        class: Positibe\Bundle\CoreBundle\Twig\Extension\PositibeCoreExtension
        arguments: [@service_container]
        tags:
          - { name: twig.extension }

    #@fixme To remove after ResourceBundle 1.0 official release
    sylius.resource_controller.form_factory:
        class: Positibe\Bundle\CoreBundle\Controller\ResourceFormFactory
        arguments: ["@form.factory"]