services:
    positibe_core.core_extension:
        class: Positibe\Bundle\FilterBundle\Twig\Extension\PositibeCoreExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    positibe_core.form_type_extension:
        class: Positibe\Bundle\FilterBundle\Form\Extension\FormTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    positibe_core.entity_ajax_form_type:
        class: Positibe\Bundle\FilterBundle\Form\Type\EntityAjaxFormType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }