sylius_resource:
    settings:
        sortable: true
        filterable: true
        paginate: $paginate
    resources:
        positibe.page:
            driver: doctrine/orm
            templates: PositibeOrmContentBundle:Page
            classes:
                model:      Positibe\Bundle\OrmContentBundle\Entity\Page
                controller: Positibe\Bundle\CoreBundle\Controller\TranslatableController
                repository: Positibe\Bundle\OrmContentBundle\Entity\Repository\PageRepository
        positibe.category:
            driver: doctrine/orm
            templates: PositibeOrmContentBundle:Category
            classes:
                model:      Positibe\Bundle\OrmContentBundle\Entity\Category
                controller: Positibe\Bundle\CoreBundle\Controller\TranslatableController
                repository: Positibe\Bundle\OrmContentBundle\Entity\Repository\CategoryRepository
        positibe.menu:
            driver: doctrine/orm
            templates: PositibeOrmContentBundle:Menu
            classes:
                model:      Positibe\Bundle\OrmContentBundle\Entity\MenuNode
                controller: Positibe\Bundle\CoreBundle\Controller\TranslatableController
                repository: Positibe\Bundle\OrmContentBundle\Entity\Repository\MenuNodeRepository
        positibe.block:
            driver: doctrine/orm
            templates: PositibeOrmContentBundle:Block
            classes:
                model:      Positibe\Bundle\OrmContentBundle\Entity\Abstracts\AbstractVisibilityBlock
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: Positibe\Bundle\OrmContentBundle\Entity\Repository\BlockRepository
        positibe.menu_block:
            driver: doctrine/orm
            templates: PositibeOrmContentBundle:MenuBlock
            classes:
                model:      Positibe\Bundle\OrmContentBundle\Entity\Blocks\MenuBlock
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: Positibe\Bundle\OrmContentBundle\Entity\Repository\BlockRepository
        positibe.content_block:
            driver: doctrine/orm
            templates: PositibeOrmContentBundle:ContentBlock
            classes:
                model:      Positibe\Bundle\OrmContentBundle\Entity\Blocks\ContentBlock
                controller: Positibe\Bundle\CoreBundle\Controller\TranslatableController
                repository: Positibe\Bundle\OrmContentBundle\Entity\Repository\BlockRepository
        positibe.page_block:
            driver: doctrine/orm
            templates: PositibeOrmContentBundle:PageBlock
            classes:
                model:      Positibe\Bundle\OrmContentBundle\Entity\Blocks\PageBlock
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: Positibe\Bundle\OrmContentBundle\Entity\Repository\BlockRepository
        positibe.gallery_block:
            driver: doctrine/orm
            templates: PositibeOrmContentBundle:GalleryBlock
            classes:
                model:      Positibe\Bundle\OrmContentBundle\Entity\Blocks\GalleryBlock
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: Positibe\Bundle\OrmContentBundle\Entity\Repository\BlockRepository