services:
# You have to activate it when are not using CmfCoreBundle
#    twig.extension.text:
#        class: Twig_Extensions_Extension_Text
#        tags:
#            - { name: twig.extension }

    intl.twig.extension:
        class: Twig_Extensions_Extension_Intl
        tags: [{ name: 'twig.extension' }]